version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - 'main'

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.9

    environment:
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - checkout
      # Step 1: Setup job
      - run:
          name: Setup job
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      # Step 1: Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            cd ..
            zip -r9 function.zip . -i project/*
            aws s3 cp function.zip s3://deployments-pleb/function.zip

      # Step 4: Deploy code
      - run:
          name: Deploy code
          command: |
            aws lambda update-function-configuration \
              --function-name hello_world \
              --code S3Bucket=deployments-pleb,S3Key=function.zip
      # Step 5: Test function
      - run:
          name: Test function
          command: |
            echo '{}' | aws lambda invoke \
              --function-name hello_world \
              --payload file://dev/null \
              response.json

      # Step 6: Store artifacts
      - store_artifacts:
          path: response.json
          destination: response.json
