version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.9

    environment:
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - checkout

      # Step 1: Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Step 2: Package code
      - run:
          name: Package code
          command: |
            zip -r $CIRCLE_ARTIFACTS/function.zip .

      # Step 3: Download code
      - run:
          name: Download code
          command: |
            aws s3 cp s3://deployments-pleb/function.zip .

      # Step 4: Deploy code
      - run:
          name: Deploy code
          command: |
            aws lambda update-function-code \
              --function-name hello_world \
              --zip-file fileb://function.zip

      # Step 5: Test function
      - run:
          name: Test function
          command: |
            echo '{}' | aws lambda invoke \
              --function-name hello_world \
              --payload file://dev/null \
              response.json

      # Step 6: Store artifacts
      - store_artifacts:
          path: response.json
          destination: response.json
